###注册 中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 82
###网关名称 注册中心的别名
spring:
  application:
    name: app-zuul
#  cloud:
#    config:
#      ####读取后缀
#      profile: dev
#      ####读取config-server注册地址
#      discovery:
#        service-id: config-server
#        enabled: true
###开启断点监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

### 配置网关反向代理 客户端不知道会员服务和订单服务的实际地址 配置过滤规则 api-a/api-b随便写
zuul:
  routes:
    api-a:
      ### 以 /api-member/访问转发到会员服务
      path: /api-a/**
      serviceId: app-encyption
    api-b:
      ### 以 /api-order/访问转发到订单服务
      path: /api-b/**
      serviceId: app-message